[package]
name = "integrations_api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
axum = "0.7"
config = "0.15.11"
dotenvy = "0.15.7"
lapin = "2.5.3"
reqwest = { version = "0.12.15", features = ["json", "rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.16.0", features = ["v4", "v7"] }
