services:
  init:
    image: grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    networks:
      - observability
    volumes:
      - tempo-storage:/var/tempo

  tempo:
    image: grafana/tempo:latest
    command: [ "--config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml:ro
      - tempo-storage:/var/tempo
    ports:
      - "3200:3200"
      - "4317"
    depends_on:
      - init
    restart: always
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQlStreaming metricsSummary
    ports:
      - "3000:3000"
    networks:
      - observability
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - ./rules.yaml:/etc/prometheus/rules.yaml:ro
    restart: always
    networks:
      - observability

  alertmanager:
    image: prom/alertmanager:latest
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
      - --web.external-url=http://alertmanager:9093
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yaml:/etc/alertmanager/alertmanager.yml
      - alertmanager-storage:/alertmanager
    restart: always
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: [ "--config.file=/etc/loki/loki-config.yaml" ]
    networks:
      - observability
    restart: always
    volumes:
      - loki-storage:/loki
      - ./loki.yaml:/etc/loki/loki-config.yaml:ro

  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"
    restart: always
    networks:
      - observability

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector.yaml" ]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "9464:9464"
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    networks:
      - observability

networks:
  observability:


volumes:
  grafana-storage:
  tempo-storage:
  prometheus-storage:
  loki-storage:
  alertmanager-storage:
