environment = "local"

[application]
host = "0.0.0.0"
port = 8000

[database]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "password"
database_name = "integrations"
require_ssl = false

[rabbitmq]
url = "amqp://guest:guest@127.0.0.1:5672/%2F"
exchange_name = "default_exchange"
queues = [
  { registry = "crates.io", queue_name = "integration.crates.io" },
  { registry = "crates.io", queue_name = "integration.crates.io.parser" },
  { registry = "jsr.io", queue_name = "integration.jsr.io" },
  { registry = "jsr.io", queue_name = "integration.jsr.io.parser" },
  { registry = "npmjs.com", queue_name = "integration.npmjs.com" },
  { registry = "npmjs.com", queue_name = "integration.npmjs.com.parser" },
]
queue_consumer = "consumer"

[minio]
url = "http://127.0.0.1:9000"
username = "minioadmin"
password = "minioadmin"
