[application]
host = "127.0.0.1"
port = 8000

[database]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "password"
database_name = "integrations"
require_ssl = false

[rabbitmq]
url = "amqp://guest:guest@127.0.0.1:5672/%2F"
exchange_name = "default_exchange"
queues = [
  "integration.crates.io",
  "integration.crates.io.parser",
  "integration.jsr.io",
  "integration.jsr.io.parser",
  "integration.npmjs.com",
  "integration.npmjs.com.parser",
]
queue_consumer = "consumer"
registry_queues = [
  [
    "crates.io",
    "integration.crates.io",
  ],
  [
    "jsr.io",
    "integration.jsr.io",
  ],
  [
    "npmjs.com",
    "integration.npmjs.com",
  ],
]

[minio]
url = "http://127.0.0.1:9000"
username = "minioadmin"
password = "minioadmin"
